// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    ScopeSelector: require('./scope-selector'),
    GrammarRegistry: require('./grammar-registry'),
    Grammar: require('./grammar')
  };

}).call(this);
